#WEB 端口
server:
  port: 8030
#服务名
spring:
  application:
    name: xiachen-mall-user
  rabbitmq:
    addresses: 182.92.200.48
    port: 15672
    username: guest
    password: guest
  thymeleaf:
    enabled: true