server:
  port: 8040
spring:
  application:
    name: xiachen-mall-order

  rabbitmq:
    addresses: 182.92.200.48
    port: 15672
    username: guest
    password: guest
# 订单服务只提供接口服务，不提供页面提示信息
  thymeleaf:
    enabled: false
